logger:
  enable: {{ get_env(name="LOGGER_ENABLE") }}
  pretty_backtrace: {{ get_env(name="LOGGER_PRETTY_BACKTRACE") }}
  level: {{ get_env(name="LOGGER_LEVEL") }}
  format: {{ get_env(name="LOGGER_FORMAT") }}

server:
  port: {{ get_env(name="PORT") }}
  binding: {{ get_env(name="SERVER_BINDING") }}
  host: {{ get_env(name="SERVER_HOST") }}
  middlewares:

workers:
  mode: {{ get_env(name="WORKER_MODE") }}

queue:
  kind: Redis
  uri: {{ get_env(name="REDIS_URL") }}
  dangerously_flush: {{ get_env(name="REDIS_DANGEROUSLY_FLUSH") }}

settings:
  email:
    provider: ses
    from: {{ get_env(name="EMAIL_FROM") }}
    timeout_seconds: {{ get_env(name="EMAIL_TIMEOUT") }}
    rate_limit_ms: {{ get_env(name="EMAIL_RATE_LIMIT") }}
    retry:
      max_attempts: 3
      backoff_base: 2

  sms:
    provider: speedsms
    access_token: {{ get_env(name="SPEEDSMS_ACCESS_TOKEN") }}
    timeout_seconds: {{ get_env(name="SMS_TIMEOUT") }}
    rate_limit_ms: {{ get_env(name="SMS_RATE_LIMIT") }}
    retry:
      max_attempts: 3
      backoff_base: 2
  vision:
    project_id: {{ get_env(name="GOOGLE_VISION_PROJECT_ID") }}
    key_path: {{ get_env(name="GOOGLE_VISION_KEY_PATH") }}

database:
  uri: {{ get_env(name="DATABASE_URL") }}
  enable_logging: {{ get_env(name="DATABASE_ENABLE_LOGGING") }}
  connect_timeout: {{ get_env(name="DB_CONNECT_TIMEOUT") }}
  idle_timeout: {{ get_env(name="DB_IDLE_TIMEOUT") }}
  min_connections: {{ get_env(name="DB_MIN_CONNECTIONS") }}
  max_connections: {{ get_env(name="DB_MAX_CONNECTIONS") }}
  auto_migrate: {{ get_env(name="DATABASE_AUTO_MIGRATE") }}
  dangerously_truncate: {{ get_env(name="DATABASE_DANGEROUSLY_TRUNCATE") }}
  dangerously_recreate: {{ get_env(name="DATABASE_DANGEROUSLY_RECREATE") }}

auth:
  jwt:
    secret: {{ get_env(name="JWT_SECRET") }}
    expiration: {{ get_env(name="JWT_EXPIRATION") }}
