# Loco configuration file documentation

# Application logging configuration
logger:
  # Enable or disable logging.
  enable: true
  # Enable pretty backtrace (sets RUST_BACKTRACE=1)
  pretty_backtrace: true
  # Log level, options: trace, debug, info, warn or error.
  level: debug
  # Define the logging format. options: compact, pretty or json
  format: compact

# Web server configuration
server:
  # Port on which the server will listen. the server binding is 0.0.0.0:{PORT}
  port: 5150
  # The UI hostname or IP address that mailers will point to.
  host: http://localhost
  middlewares:

# Worker Configuration
workers:
  mode: ForegroundBlocking

# Queue Configuration
queue:
  kind: Redis
  # Redis connection URI
  uri: '{{ get_env(name="REDIS_URL", default="redis://127.0.0.1") }}'
  dangerously_flush: false

# Mailer Configuration.
mailer:
  stub: true
  smtp:
    enable: true
    host: localhost
    port: 1025
    secure: false

# Database Configuration
database:
  uri: '{{ get_env(name="DATABASE_URL", default="postgres://nhatroso:nhatroso@localhost:5433/nhatroso_db_test") }}'
  enable_logging: false
  connect_timeout: 500
  idle_timeout: 500
  min_connections: 1
  max_connections: 1
  auto_migrate: true
  dangerously_truncate: true
  dangerously_recreate: true

# Authentication Configuration
auth:
  jwt:
    secret: FKAvOMDFPCthP6yZAl6e
    expiration: 604800
