//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "contracts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub room_id: Uuid,
    pub start_date: Date,
    pub end_date: Date,
    pub monthly_rent: i32,
    pub deposit_amount: i32,
    pub payment_day: i32,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub rental_period: i32,
    pub room_code: String,
    pub room_address: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::contract_tenants::Entity")]
    ContractTenants,
    #[sea_orm(
        belongs_to = "super::rooms::Entity",
        from = "Column::RoomId",
        to = "super::rooms::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Rooms,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::contract_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractTenants.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rooms.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::contract_tenants::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contract_tenants::Relation::Contracts.def().rev())
    }
}
