//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "floors")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub building_id: Uuid,
    pub block_id: Uuid,
    pub identifier: String,
    pub status: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::blocks::Entity",
        from = "Column::BlockId",
        to = "super::blocks::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Blocks,
    #[sea_orm(
        belongs_to = "super::buildings::Entity",
        from = "Column::BuildingId",
        to = "super::buildings::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Buildings,
    #[sea_orm(has_many = "super::rooms::Entity")]
    Rooms,
}

impl Related<super::blocks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Blocks.def()
    }
}

impl Related<super::buildings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buildings.def()
    }
}

impl Related<super::rooms::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Rooms.def()
    }
}
