//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "invoices")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub room_code: Option<String>,
    pub tenant_name: Option<String>,
    pub total_amount: Option<Decimal>,
    pub status: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::invoice_details::Entity")]
    InvoiceDetails,
    #[sea_orm(has_many = "super::invoice_status_histories::Entity")]
    InvoiceStatusHistories,
}

impl Related<super::invoice_details::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvoiceDetails.def()
    }
}

impl Related<super::invoice_status_histories::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InvoiceStatusHistories.def()
    }
}
