//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "meter_readings")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub meter_id: Uuid,
    pub reading_value: Decimal,
    pub reading_date: DateTimeWithTimeZone,
    pub image_url: Option<String>,
    pub created_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::meters::Entity",
        from = "Column::MeterId",
        to = "super::meters::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Meters,
}

impl Related<super::meters::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Meters.def()
    }
}
