//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub mod prelude;

pub mod buildings;
pub mod contract_tenants;
pub mod contracts;
pub mod floors;
pub mod meter_readings;
pub mod meters;
pub mod price_rules;
pub mod refresh_tokens;
pub mod room_services;
pub mod rooms;
pub mod services;
pub mod users;
