//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::buildings::Entity as Buildings;
pub use super::contract_tenants::Entity as ContractTenants;
pub use super::contracts::Entity as Contracts;
pub use super::floors::Entity as Floors;
pub use super::invoice_details::Entity as InvoiceDetails;
pub use super::invoice_status_histories::Entity as InvoiceStatusHistories;
pub use super::invoices::Entity as Invoices;
pub use super::meter_readings::Entity as MeterReadings;
pub use super::meter_request_configs::Entity as MeterRequestConfigs;
pub use super::meter_requests::Entity as MeterRequests;
pub use super::meters::Entity as Meters;
pub use super::price_rules::Entity as PriceRules;
pub use super::refresh_tokens::Entity as RefreshTokens;
pub use super::room_services::Entity as RoomServices;
pub use super::rooms::Entity as Rooms;
pub use super::services::Entity as Services;
pub use super::users::Entity as Users;
