//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub email: Option<String>,
    #[sea_orm(unique)]
    pub phone: String,
    pub password_hash: String,
    pub role: String,
    pub status: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    pub name: String,
    pub id_card: Option<String>,
    pub id_card_date: Option<Date>,
    pub address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::auto_invoice_configs::Entity")]
    AutoInvoiceConfigs,
    #[sea_orm(has_many = "super::buildings::Entity")]
    Buildings,
    #[sea_orm(has_many = "super::contract_tenants::Entity")]
    ContractTenants,
    #[sea_orm(has_many = "super::contracts::Entity")]
    Contracts,
    #[sea_orm(has_many = "super::meter_request_configs::Entity")]
    MeterRequestConfigs,
    #[sea_orm(has_many = "super::price_rules::Entity")]
    PriceRules,
    #[sea_orm(has_many = "super::refresh_tokens::Entity")]
    RefreshTokens,
    #[sea_orm(has_many = "super::services::Entity")]
    Services,
}

impl Related<super::auto_invoice_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AutoInvoiceConfigs.def()
    }
}

impl Related<super::buildings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Buildings.def()
    }
}

impl Related<super::contract_tenants::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContractTenants.def()
    }
}

impl Related<super::meter_request_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MeterRequestConfigs.def()
    }
}

impl Related<super::price_rules::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PriceRules.def()
    }
}

impl Related<super::refresh_tokens::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RefreshTokens.def()
    }
}

impl Related<super::services::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Services.def()
    }
}

impl Related<super::contracts::Entity> for Entity {
    fn to() -> RelationDef {
        super::contract_tenants::Relation::Contracts.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::contract_tenants::Relation::Users.def().rev())
    }
}
